### ISSUE TITLE
What is the latest `openapi.yaml` file for the broker API

### ISSUE THREAD

**Issue by br-follow** [alpacahq/alpaca-docs#12]
It looks like the version at https://github.com/alpacahq/bkdocs/blob/master/assets/openapi.yaml has been deprecated. However, it appears to have updates that are not in the version in this repo.

Could you clarify which is the source of truth?

**Comment by drew887** [comment]
Hey @br-allstreet sorry for the late reply on this, but the source of truth going forward should be the one found in this repo. 

If you happen to remember, do you know what the updates that aren't in this repo were? Just to make sure they were purposely removed and not just some that we missed? :see_no_evil:

**Comment by br-allstreet** [comment]
Hmm...I can't find the diffs anymore.
