### ISSUE TITLE
Endpoint not found

### ISSUE THREAD

**Issue by Nahasean94** [alpacahq/alpaca-docs#17]
Following the doc on[ this page](https://alpaca.markets/docs/api-references/trading-api/assets/#example), `v2` endpoint returns an error:

`{
    "message": "endpoint not found."
}`

But using `v1`, things seem ok. An update to the docs is needed

**Comment by drew887** [comment]
Hey @Nahasean94  the v2 endpoints for assets still work for me, I'm curious what was the full url you tried to use? :thinking:

**Comment by Nahasean94** [comment]
https://broker-api.sandbox.alpaca.markets/v2/assets

**Comment by drew887** [comment]
Ah you're using the broker api, The docs you linked to are for the trading api, which is on v2. 

The docs for the broker api [assets endpoint are here](https://alpaca.markets/docs/api-references/broker-api/assets/#retrieving-all-assets) and still reference v1
